2025-06-23 08:01:34,265 INFO    MainThread:2352322 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-23 08:01:34,265 INFO    MainThread:2352322 [wandb_setup.py:_flush():81] Configure stats pid to 2352322
2025-06-23 08:01:34,265 INFO    MainThread:2352322 [wandb_setup.py:_flush():81] Loading settings from /home/thiago-bittencourt/.config/wandb/settings
2025-06-23 08:01:34,265 INFO    MainThread:2352322 [wandb_setup.py:_flush():81] Loading settings from /home/thiago-bittencourt/fc-projeto-final/wandb/settings
2025-06-23 08:01:34,265 INFO    MainThread:2352322 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-23 08:01:34,265 INFO    MainThread:2352322 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/thiago-bittencourt/fc-projeto-final/wandb/run-20250623_080134-3rq8af3q/logs/debug.log
2025-06-23 08:01:34,266 INFO    MainThread:2352322 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/thiago-bittencourt/fc-projeto-final/wandb/run-20250623_080134-3rq8af3q/logs/debug-internal.log
2025-06-23 08:01:34,266 INFO    MainThread:2352322 [wandb_init.py:monkeypatch_ipython():622] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x759951480c20>
2025-06-23 08:01:34,266 INFO    MainThread:2352322 [wandb_init.py:init():831] calling init triggers
2025-06-23 08:01:34,266 INFO    MainThread:2352322 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'batch_size': 64, 'epochs': 20, 'learning_rate': 0.001, 'model': 'DCNN08', 'fault_type': 'outer', '_wandb': {}}
2025-06-23 08:01:34,266 INFO    MainThread:2352322 [wandb_init.py:init():872] starting backend
2025-06-23 08:01:34,473 INFO    MainThread:2352322 [wandb_init.py:init():875] sending inform_init request
2025-06-23 08:01:34,478 INFO    MainThread:2352322 [wandb_init.py:init():883] backend started and connected
2025-06-23 08:01:34,481 INFO    MainThread:2352322 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2025-06-23 08:01:34,482 INFO    MainThread:2352322 [wandb_init.py:init():956] updated telemetry
2025-06-23 08:01:34,492 INFO    MainThread:2352322 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-23 08:01:35,036 INFO    MainThread:2352322 [wandb_init.py:init():1032] starting run threads in backend
2025-06-23 08:01:35,100 INFO    MainThread:2352322 [wandb_run.py:_console_start():2453] atexit reg
2025-06-23 08:01:35,100 INFO    MainThread:2352322 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-23 08:01:35,100 INFO    MainThread:2352322 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-23 08:01:35,100 INFO    MainThread:2352322 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-23 08:01:35,101 INFO    MainThread:2352322 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-23 08:01:35,101 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:35,104 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:35,104 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:01:45,210 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:45,214 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:45,214 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:01:45,215 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:45,218 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:45,218 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:01:45,218 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:45,220 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:45,220 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:01:45,222 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:45,224 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:45,224 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:01:45,224 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:45,226 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:45,226 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:01:45,227 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:45,229 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:45,229 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:01:45,229 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:45,231 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:45,231 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:01:45,490 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-06-23 08:01:45,493 INFO    MainThread:2352322 [jupyter.py:save_ipynb():404] [no run ID] not saving jupyter notebook
2025-06-23 08:01:45,493 INFO    MainThread:2352322 [wandb_init.py:_pre_run_cell_hook():581] [no run ID] pausing backend
2025-06-23 08:02:07,504 WARNING MsgRouterThr:2352322 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/thiago-bittencourt/fc-projeto-final/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-23 08:02:07,505 INFO    MsgRouterThr:2352322 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-23 08:02:07,698 INFO    MainThread:2352322 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
